version: '3.8'

services:
  app:
    build: .
    ports:
      - "2222:2222"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/profiledb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:2222/api/health/ping"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 30s
    networks:
      - profile-network
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=profiledb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - profile-network
    restart: unless-stopped

networks:
  profile-network:
    driver: bridge

volumes:
  postgres_data:
