name: Build and Test

on:
  workflow_call:
    outputs:
      build-status:
        description: "Build status"
        value: ${{ jobs.build.outputs.status }}

jobs:
  build:
    name: Build, Test, and Push Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      status: ${{ steps.build.outputs.status }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      
      - name: Build with Maven
        id: build
        run: |
          mvn -B clean package
          echo "status=success" >> $GITHUB_OUTPUT
      
      - name: Run Tests
        run: mvn test
      
      - name: Generate Test Reports
        run: mvn surefire-report:report
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/portfolio-builder:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/portfolio-builder:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            target/site/
            target/surefire-reports/
          retention-days: 30
          if-no-files-found: warn
          compression-level: 9
