name: Build and Test

on:
  workflow_call:
    outputs:
      build-status:
        description: "Build status"
        value: ${{ jobs.build.outputs.status }}

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.build.outputs.status }}
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      
      - name: Build with Maven
        id: build
        run: |
          mvn -B clean package
          echo "status=success" >> $GITHUB_OUTPUT
      
      - name: Run Tests
        run: mvn test
      
      - name: Generate Test Reports
        run: mvn surefire-report:report
      
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-build
          path: target/*.jar
      
      - name: Upload Test Reports
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: target/site/
