name: Tag Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Metadata
        id: metadata
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/koodo-product
          tags: |
            type=ref,event=tag
            type=semver,pattern={{version}}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.metadata.outputs.tags }}

    #  - name: Deploy to Production
     #   uses: google-github-actions/deploy-cloudrun@v1
    #    with:
     #     service: koodo-product-prod
     #     image: ${{ secrets.DOCKERHUB_USERNAME }}/koodo-product:${{ steps.metadata.outputs.tags }}
     #     credentials: ${{ secrets.GCP_SA_KEY }}
     #     region: us-central1
     #     allow_unauthenticated: true
